### ISSUE TITLE
Does this require Ser2Sock or can it work with /dev/ttyUSB0

### ISSUE THREAD

**Issue by skarragallagher** [TD22057/ad-mqtt#1]
Hi I am trying to get this working. I have an A2DUSB that is connected directly to the Home Assistant Server (Debian 11) latest HA. I was having problems with RF zones not resetting, It will fault correctly but they never reset. I came across this as possible work around. I was having issues building the ser2sock in Debian 11 for some reason so i was wondering if it could access the port directly or if it required ser2sock. Also can you can example of where the ser2sock or /dev/ goes in the config file? Any help here would be greatly appreciated

**Comment by TD22057** [comment]
It only works w/ ser2sock - serial connections require different network code than TCP servers.

**Comment by skarragallagher** [comment]
Okay thanks for the fast reply, i appreciate it. I will try to figure out how to make the ser2sock source code work on Debian 11. Is there anything that needs to be done on the home assistant side to set stuff up? Like on the mqqt side? Thanks again 

Cheers

**Comment by TD22057** [comment]
On the HA side the answer is it depends.  I don't run the HASS operating system (I forget the name - supervised?).  If you're running HA in a docker container or just from source, you just run ad2mqtt somewhere else.  I have mine set up with a system.d startup script to insure it starts when the OS boots.  ad2mqtt (just like ser2sock) is just a separate application.  It just needs access to the MQTT broker. 

If you're running HA in supervisor mode where it controls the whole OS and all the processes, then you're on your own.  In theory you can make a docker container to run ad2mqtt inside HA but I don't work that way so I'd have to go learn how it works and set up some kind of test env (so that's not happening on my end).

**Comment by skarragallagher** [comment]
Thanks for that, Yeah I am running in a docker container on Debian 11 for the primary purpose of having the ability to run other services etc. I have socat service connecting to my networked Zwave controller. So it should be straightforward once I get past the ser2sock build issues. I appreciate the help, I recently switched from Homeseer to Home Assistant so i am little green with MQTT and all the other stuff but i have a lot automations built off the security zones and am looking forward to getting those all working again.

**Comment by TD22057** [comment]
What problems are you having?  IMO I wouldn't try using their deb build instructions. Just use the makefile and get it to compile.  You can manually install it and run it then.

**Comment by skarragallagher** [comment]
Thanks for the tip, I did the makefile method and it worked. I was able to get up and running and connected via telnet on the port and it was successfully printing data properly. I then moved on to getting your script working. I got it successfully started with commenting out all my RF zones. I have yet to see what i need to do to see these in now in HomeAssistant but I noticed there was no where to put a loop value of my wireless zones. Also it seems to complain about the format that i put the rfid

The error i got before commenting out was `ValueError: invalid literal for int() with base 10: 'A1234567'`

Do i omit the A?

**Comment by TD22057** [comment]
Turn on debugging and toggle the zone.  You should see the zone ID in the debug message and you can paste that into the config.  At least for me, all RF ID's were integers.

**Comment by skarragallagher** [comment]
I will investigate the rf zone errors. Thanks for the tip. For now i see that it failed Here is the list of errors. I will investigate these to see if i can't determine what is missing. 

`root@HomeAssistant:~/ad-mqtt# ./run.py
Traceback (most recent call last):
  File "/root/ad-mqtt/./run.py", line 67, in <module>
    ad_mqtt.run.run(host, port, alarm_code, zone_data, log_level=log_level, log_screen=log_screen, log_file=log_file)
  File "./ad_mqtt/run.py", line 49, in run
    loop.select()
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/insteon_mqtt/network/poll.py", line 229, in select
    if link.read_from_link() == -1:
  File "./ad_mqtt/Client.py", line 115, in read_from_link
    self.parse_read_buf()
  File "./ad_mqtt/Client.py", line 133, in parse_read_buf
    self.on_read(data=line)
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/alarmdecoder/event/event.py", line 84, in fire
    func(self.obj, *args, **kwargs)
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/alarmdecoder/decoder.py", line 1041, in _on_read
    self._handle_message(data)
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/alarmdecoder/decoder.py", line 439, in _handle_message
    msg = self._handle_keypad_message(data)
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/alarmdecoder/decoder.py", line 481, in _handle_keypad_message
    self._update_internal_states(msg)
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/alarmdecoder/decoder.py", line 632, in _update_internal_states
    self._update_zone_tracker(message)
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/alarmdecoder/decoder.py", line 1017, in _update_zone_tracker
    self._zonetracker.update(message)
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/alarmdecoder/zonetracking.py", line 207, in update
    self._add_zone(zone, status=status)
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/alarmdecoder/zonetracking.py", line 336, in _add_zone
    self._update_zone(zone, status=status)
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/alarmdecoder/zonetracking.py", line 366, in _update_zone
    self.on_fault(zone=zone)
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/alarmdecoder/event/event.py", line 84, in fire
    func(self.obj, *args, **kwargs)
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/alarmdecoder/decoder.py", line 1053, in _on_zone_fault
    self.on_zone_fault(*args, **kwargs)
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/alarmdecoder/event/event.py", line 84, in fire
    func(self.obj, *args, **kwargs)
  File "./ad_mqtt/Bridge.py", line 198, in on_zone_fault
    self.publish(self.sensor_state_topic, {}, payload, zone=zone)
  File "./ad_mqtt/Bridge.py", line 141, in publish
    payload_args["zone"] = info["entity"]
TypeError: 'NoneType' object is not subscriptable
`

Thanks again for all the help

**Comment by TD22057** [comment]
That looks like the input zone_data dict is wrong.  Did you turn on debugging and look at the log messages to get the zone numbers?  What does your zone_data dict look like?

**Comment by skarragallagher** [comment]
Yeah i had incomplete zone information. Looks like it is running with no errors now. I don't see the zones in Home Assistant as being updated yet but i do see some of them in the MQQT Integration. I will continue to investigate. One thing i think i will need to do is figure out how to pass the loop number because i have one wireless device operating 2 separate loops

**Comment by TD22057** [comment]
I think the loop is somewhere in alarmdecoder.  I don't have any devices like that so I didn't bother figuring it out.  If you find it and point me to any info on I can try and make an update.  Or feel free to fork and try an update yourself if you want

**Comment by skarragallagher** [comment]
Thank you! Its probably a bit over my head. Let me try to find the documentation on it

**Comment by skarragallagher** [comment]
Aside from the loop issue, it appears that i do have it working now. I had to remove the Alarm Decoder Integration and restart a couple times. Then i removed the Mosquitto broker Integration and modified the run.py and made sure the entity ids were unique. The problem i believe was name conflicts.  It looks like zones are resetting as expected and all zones are showing. Thanks again for writing this. I will take a look tomorrow to see if i can't find the place to input the loop. Cheers

**Comment by TD22057** [comment]
I think I found it: https://alarmdecoder.readthedocs.io/en/latest/alarmdecoder/#alarmdecoder.messages.RFMessage

Rough work order:
- update log output to print the loop info out of the message so you can see what's triggering
- add an optional loop input to the zone_data
- index on both the zone and loop index in that case when searching for info

I'll try and work on it a little this weekend

**Comment by skarragallagher** [comment]
I really appreciate it. Thank you. Side question, do you know where to set the time out value, I have a lot of zones and noticed when i had most of them open, that the would flap open/closed. I think i need to adjust the timeout value. Any guidance there would be great.

**Comment by TD22057** [comment]
Time out for what?  I'm not sure what kind of value you're talking about.  Turn on debugging and check the logs - messages should only arrive when the sensor value changes.

**Comment by skarragallagher** [comment]
Hmm, interesting. I thought it used a time out somehow to turn off zones unless it got a new message... almost like an auto off.  I will investigate the logs and see what is going on. It works great when most zones are closed and only a few are open. I will try to debug it.

**Comment by TD22057** [comment]
Closed.  RF loops have been added.

**Comment by skarragallagher** [comment]
Schweet! Thank you. Appreciate this greatly!
