### ISSUE TITLE
Reset all zones when alarm is reset?

### ISSUE THREAD

**Issue by skarragallagher** [TD22057/ad-mqtt#2]
Is there a way (and is would it be desirable) to create a way to reset all zones upon turning off the alarm (entering code+1). I ran into this scenario when setting this up initially because the zones show up automatically but they have the unknown status until they are opened or closed. I have some windows that are really high up that i need a ladder to open and close and to get it to display the proper status I had to get out that ladder and manually open/close. No big deal right? you do it once and thats it. Well unfortunately the last few days i have been having issues with MQTT broker that is installed inside Home Assistant where by i needed to actually remove that and run it outside of Home Assistant and on the host itself. After resetting everything, i now have the "unknown" zones problem again. I am assuming this will come up again in the future as we are tinkerers.

I have seen other alarm decoder integrations that use that method of resetting all zones to the closed state upon turning off the alarm. If you have any other ideas as well to overcome this too let me know. Appreciate the work you have done on this, it is integral to my setup now :)

**Comment by TD22057** [comment]
See new config option in run.py: https://github.com/TD22057/ad-mqtt/blob/main/run.py#L14 which will send out an MQTT message saying every zone is closed (not faulted) on startup.

**Comment by skarragallagher** [comment]
Awesome Thank you!
