### ISSUE TITLE
Is there any way to use a custom mqtt host?

### ISSUE THREAD

**Issue by SantiagoSotoC** [TD22057/ad-mqtt#3]
Hi, I`m using Home Assistant mqtt addon, there is any way to use a custom host ?  What about username and password?

**Comment by SantiagoSotoC** [comment]
I start to add support myself

**Comment by TD22057** [comment]
See new run.py and ad_mqtt/Config.py class.  Full set of mqtt options (broker, port, user/pass, encryption) can now be input.
