### ISSUE TITLE
Add rf_loop for rf zones 

### ISSUE THREAD

**Issue by SantiagoSotoC** [TD22057/ad-mqtt#6]

**Comment by TD22057** [comment]
See new run.py.  RfZone object will build a an RF zone for the simple case (one loop).  Rf config object can be built with a loop list to define the zones for each loop in the RF device.

**Comment by skarragallagher** [comment]
I built this again from scratch, and modified the zones according to the notes. I have basically 1 zone that is giving me two loops. In the run.py i have this code

`    AD.Rf( "12345", loops=[
        AD.Zone(23, "mqqt_front_driveway_beam", "Front Driveway Beam"),
        AD.Zone(25, "mqqt_fence_gate", "Fence Gate"),
        None,None,
        ]),
`
Representing Loop 1, Loop 2 and which are in use and 3/4 not in use.

When I execute the run.py i get this 
`root@HomeAssistant:~/ad-mqtt# ./run.py
Traceback (most recent call last):
  File "/root/ad-mqtt/./run.py", line 62, in <module>
    AD.Rf( "0302767", loops=[
  File "./ad_mqtt/Devices.py", line 35, in __init__
    l.has_battery = True
AttributeError: 'NoneType' object has no attribute 'has_battery'
`

If i comment out the block above the service runs fine. I did have to add the double quotes over the rfid as it was throwing other errors prior. Any idea whats going on there.  The device is a honeywell 5816OD https://fccid.io/CFS8DL5816OD-1/User-Manual/manual-1428109.

Loop one is an external contact switch. and Loop 2 is the built in magnet sensor. 

I tried setting the ad_mqtt/Devices.py has_battery section listed in the error as False. I am wondering if the Loop 2 has the attribute has_battery and loop 1 which is the external contact switch doesn't have that attribute.

**Comment by TD22057** [comment]
Fixed.  Currently there is no entity in HASS for the device - just the zones.  I'm not sure HASS can have a virtual device made from MQTT at all anyway. So a battery entity is created for each zone (which is each loop).  If you have 2 active loops, they'll both end up w/ a battery entity which will report the same value.

**Comment by skarragallagher** [comment]
Got past the battery issue... Now i have this..

root@HomeAssistant:~/ad-mqtt# ./run.py
Traceback (most recent call last):
  File "/root/ad-mqtt/./run.py", line 77, in <module>
    AD.run.run(cfg, alarm_code, devices)
  File "./ad_mqtt/run.py", line 39, in run
    zones, rf_devices = Devices.init_devices(devices)
  File "./ad_mqtt/Devices.py", line 7, in init_devices
    zones[d.zone] = d
AttributeError: 'Rf' object has no attribute 'zone'

Thanks for looking at this again. I rebuilt the code and copied over my run.py. My code is the same for the the RF zone with loops. I checked for other differences in the file but it looks the same as is indicated.

**Comment by TD22057** [comment]
Fixed.  I wasn't using the loop inputs myself so I hadn't really run that code fully.  I set up a script to try it.  Should (hopefully) work now.

**Comment by skarragallagher** [comment]
No worries at all. Thank you so much. I will test it this evening

**Comment by skarragallagher** [comment]
Okay, it looks like the only file that changed was the Devices.py. I updated that page and it looks like that may have done it. The application starts at least. I will test it out a little bit further this evening

Thank you. Much appreciated
